# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron:  '0 0-17,19-23 * * *'
  push:
    branches: master
jobs:
  build:
    name: parse
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run main script
      run: |
        python main.py
    - name: Run covid19_data analyzing script
      run: |
        python covid19_data.py
    - name: Slack Notification
      # 前Stepの実行結果を判定
      # success() or failure() or always()
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: 'Error occurred! Please check a log!'
        SLACK_TITLE: ':fire: Data Update Error :fire:'
        SLACK_USERNAME: covid19hokkaido_scraping
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Upload screenshot
      uses: actions/upload-artifact@v1
      with:
        name: data
        path: ./data
  deploy:
    name: Build OGP
    needs: build
    runs-on: macos-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      
      - name: Download ogp images
        uses: actions/download-artifact@v1
        with:
          name: data  
          path: ./ogp
      - run: pip3 install selenium
      - run: python3 ./ogp-screenshot.py
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ogp
          publish_branch: gh-pages
